### ISSUE TITLE
Пакет является брошенным, не используйте его!

### ISSUE THREAD

**Issue by webarchitect609** [DigitalWand/digitalwand.admin_helper#121]
**Авторы! Отметьте в Packagist , что ваш пакет является заброшенным, если вы не реагируете и не исправляете его ошибки!!!**

Разработчики-пользователи данного пакета: никогда его не используйте! 

Причины: 
1 Очень низкое качество кода: почти всё на статических методах :( 
2 Для управления своей табличкой нужно делать свой модуль Битрикс. (это я попытался обойти, написав свой контроллер https://github.com/webarchitect609/bitrix-admin-helper-controller )
3 В модуле полным полно ошибок. Например, не работает массовое удаление записей. 
4 Модуль по факту является брошенным: примерно с января 2017 года сообщения об ошибках (issue) плодятся, но никто их не исправляет.

**Comment by ASGAlex** [comment]
Можете сделать лучше - напишите свой, залейте на гитхаб, используйте.
Не нравятся баги - найдите время , поправьте их, залейте рабочий пуллреквест. 

Здесь не ресурс по раздаче халявы, если у вас есть время и силы сделать свой вклад - сделайте его.  А то как будто вам тут все должны.

**Comment by webarchitect609** [comment]
Если вы авторы пакета - вы должны поддерживать его актуальность. **Если вы не планируете этого делать, то следует обозначить это для потенциальных разработчиков, оценивающих возможность использования вашего пакета на своём проекте.** 

Сыпать обвинениями в ответ на критику - это по-детски. 

Из-за того, что в вашем пакете есть довольно критичные ошибки и им неудобно пользоваться, другие его скачивают, пытаются с ним работать и зря тратят время. Потому что в итоге получается, что сил тратится больше, хотя суть в том, чтобы экономить время и силы разработчика. 

Хотя бы в README напишите, что есть ошибки или что нестабильная версия. Неужели это так трудно? 

> Можете сделать лучше - напишите свой, залейте на гитхаб, используйте.

Могу и по мере сил делаю такие пакеты. Посмотрите, сколько их у меня уже с приставкой `bitrix-*`

И если что-то нестабильное или я знаю об ошибках, то исправляю их или пишу об этом как о потенциальном недостатке, как в случае с `webarchitect609/bitrix-neverinclude`
