### ISSUE TITLE
Проект еще поддерживается?

### ISSUE THREAD

**Issue by mfilin** [DigitalWand/digitalwand.admin_helper#126]
доброго дня, собственно вопрос в топике
что с поддержкой? проект еще живой? будут ли какие то подвижки для поддержки php 8.1 ?

**Comment by ASGAlex** [comment]
Доброго дня! 

Увы для проекта, я давно уже ничего не писал ни для битрикса ни вообще для пыхи, вряд ли что-то смогу осмысленное добавить в этот проект. 
Вроде как у @nook-ru  были любопытные коммиты, стоит поинтересоваться, может у него есть версия по-свежее. 

В целом как-то так.

**Comment by mfilin** [comment]
благодарю за ответ, очень жаль

**Comment by mfilin** [comment]
для тех, кто всетаки столкнется с проблемой совместимости php8 
**bitrix\modules\digitalwand.admin_helper\lib\helper\AdminBaseHelper.php** метод **getHelperClass** нужно объявить статичным

пока больше проблем нет :)

**Comment by ASGAlex** [comment]
Так сделайте мерджреквест, и зальём в реп, если без этого не работает ;-)

**Comment by mfilin** [comment]
отправил
