### ISSUE TITLE
Автозагрузка модуля в админке

### ISSUE THREAD

**Issue by niksamokhvalov** [DigitalWand/digitalwand.admin_helper#2]
Нужно сделать так, что бы модуль автоматически загружался в админке, без необходимости вызова \Bitrix\Main\Loader. Таки образом, не будет необходимости прописывать в своих модулях подключение Админ-хелпера.

**Comment by ASGAlex** [comment]
Мне кажется, проблема сейчас не решена. 
Ну ок, подключение модуля мы не прописываем, но не это же самое страшное.
Всё равно приходится проверять, находимся ли мы на странице админки и подключать в этом случае необходимые Interface.php. Итого, избавиться от назойливого куска кода так и не получилось пока.

**Comment by niksamokhvalov** [comment]
Мы эту и многие другие проблемы решили в своём форке. Нужно лишь найти время на мерж всех наработок.

**Comment by ASGAlex** [comment]
...шли годы. Ветки расходились всё дальше...

**Comment by niksamokhvalov** [comment]
Не сыпь мне соль на сахар :-)

**Comment by may-cat** [comment]
Алексей, всё в твоих руках

**Comment by ASGAlex** [comment]
Поскольку мне не дают даже посмотреть на код, всё в руках Никиты ;-)
