### ISSUE TITLE
Нет Limit в запросах при использовании пагинации

### ISSUE THREAD

**Issue by ASGAlex** [DigitalWand/digitalwand.admin_helper#21]
Пример из жизни:
1. Заходим в список из 10 000 элементов
2. Видим первые 20 элементов
3. При этом формируется запрос без LIMIT, т.е. выбираются все 10 000 записей.

Надо, чтобы было LIMIT 0, 20 в конце такого запроса.

**Comment by Diden05** [comment]
Как в таком случае строить постраничку?

**Comment by ASGAlex** [comment]
Нужно подумать/списать с проектов, где это уже реализовано ;-) Выбор списка станет в два запроса: первый - на число элементов в таблице, второй - собственно, выборка элементов. Битрикс-то делает count() по массиву уже выбранных записей, и через то постраничка у него получается.

**Comment by senor-artemisio** [comment]
[решение проблемы](https://github.com/DigitalWand/digitalwand.admin_helper/pull/47)
