### ISSUE TITLE
При установке модуля в local все очень плохло

### ISSUE THREAD

**Issue by NPman** [DigitalWand/digitalwand.admin_helper#22]
![image](https://cloud.githubusercontent.com/assets/17519332/13375287/19a61e40-ddbd-11e5-8e63-caddf2635d1a.png)

**Comment by ASGAlex** [comment]
Есть мнение, что вообще не стоит сторонние модули ставить в local, т.к. он, как правило, под git. Иначе придётся все модули, подтянутые composer'ом, добавлять ещё и в .gitignore.

Но если таки очень хочется - ок, можно сделать фикс в /bitrix/admin/route.php, чтобы если из одного места не заинклюдилось - пробовать заинклюдить из другого.

**Comment by NPman** [comment]
Разные ситуации бывают, но видимо я один пока такой :)

**Comment by nook-ru** [comment]
Теперь при установке в `/bitrix/` все плохо — 404 в админке получаем)
