### ISSUE TITLE
Вопросы, много... в надежде разобраться что где и как

### ISSUE THREAD

**Issue by Frimko** [DigitalWand/digitalwand.admin_helper#32]
Как я понял, чтобы ваше решение работало модуль должен быть вида aloha.adminhelper 
Могу ли я это отключить?

**Comment by ASGAlex** [comment]
Это не обязательное требование. 
У классов хэлперов есть переменная $module, её можно определить вручную, указав правильное имя модуля. В противном случае ожидается, что модуль будет вида "aloha.adminhelper", да.

В недрах AdminBaseHelper (строка 130 прмерно): 

```
/**
 * @var string
 * Назвние модуля данной модели.
 * При наследовании класса необходимо указать нзвание модуля, в котором он находится.
 * А можно и не указывать, в этому случае он определится автоматически по namespace класса
 * Используется для избежания конфликтов между именами представлений.
 *
 * @api
 */
static public $module = array();
```

**Comment by Frimko** [comment]
Могу ли я работать с ORM-таблицей через ваш функционал? А не той псевдо-сущностью, что у вас в примере.

**Comment by ASGAlex** [comment]
Не понял... Можно конкретизировать:
- С какой сущностью работать хочется?
- С какой "из примера" работать не хочется?

**Comment by Frimko** [comment]
Тупанул, Извиняюсь, отличная вещь, еще бы это как библиотеку, чтобы импортировать в свои модули и вообще шик. От route.php правда придется отказаться. Либо ждать когда его включат оффициально.

**Comment by ASGAlex** [comment]
Думал над этой темой... 
Подозреваю, что проблема должна без проблем решаться копипастом, т.к. базовым классам, в общем-то, всё равно, внутри какого модуля находиться. 

Проблемы, правда, начнутся, когда захочется обновлений.
В идеале, конечно, модуль просто выкачивать и устанавливать как зависимость. Цивилизованное человечество обычно так и поступает :-)

**Comment by Frimko** [comment]
Я могу выставить платный модуль, используя вашу библиотеку(само собой с копирайтом сюда). з.ы. уж больно влом писать админку по их дрянному мануалу.

**Comment by ASGAlex** [comment]
Конечно, решение распространяется по лицензии MIT - можете использовать как угодно, только с сохранением копирайта :-)

**Comment by Frimko** [comment]
Ну лицензия то не написана, вот и спрашиваю.

**Comment by ASGAlex** [comment]
Ну почему же не написана?.. 
https://github.com/DigitalWand/digitalwand.admin_helper/blob/2.x/LICENSE.md

**Comment by Frimko** [comment]
привычка походу, лицензию внизу в описании функционала смотреть...

**Comment by Frimko** [comment]
чего-то я не догоняю... http://joxi.ru/n2Y5XRPijvxL92 ведь все правильно прописано http://joxi.ru/E2pgpWOCBPZ5km http://joxi.ru/l2Z6xnPI8x4072 и как назло первопроходцам везет на шишки

**Comment by ASGAlex** [comment]
...а HL-инфоблок-то в битриксе создан? 
Насколько я помню, чтобы он его корректно нашел, надо либо не использовать неймспепйсы, либо имя HL-инфоблока должно состоять из полного наименования класса, включая неймспейс. Только без слешей. 
Если  что - эт не я так придумал, это Битрикс всё...

**Comment by Frimko** [comment]
В этом то и дело. Что HL-блок я не использую. Я всего лишь создал orm-таблицу, и пытаюсь ее использовать. Но если я ее закину в папочку news и пропишу неймспейсы к ней и в ней, то все работает прекрасно.

**Comment by Frimko** [comment]
Либо я чего-то не догоняю

**Comment by ASGAlex** [comment]
Если цепляете к кастомной таблице, то посмотрите в сторону примера https://github.com/niksamokhvalov/demo.adminhelper - буквально вчера на его основе выбирал из b_iblock, всё работает нормально, только нужно указать таблицу у класса ЧтоНибудьTable.

**Comment by Frimko** [comment]
Я его и юзаю. Только вынес описание вашей таблицы за папочку news в папку lib. Ну и переписал неймспейсы.
З.ы.походу баг

**Comment by ASGAlex** [comment]
Если пока в коде нет ничего секретного, было бы проще мне скинуть кусок получившегося модуля - я бы посмотрел, что не так. А то пока что эффективность - как от лечения зубов по фотографии...

**Comment by Frimko** [comment]
[demo.web38.zip](https://github.com/DigitalWand/digitalwand.admin_helper/files/346999/demo.web38.zip)
вот

**Comment by Frimko** [comment]
подебажил, узнал что он просто не может найти класс надо было в include.php прописать так
`'Bitrix\Demo\Web38\NewsTable' => 'lib/NewsTable.php',`
ну и соответствующие пути в других файлах.

**Comment by niksamokhvalov** [comment]
Это ж Битрикс. У него своё понятие об автозагрузке. Посмотрите внимательно на пример: https://github.com/niksamokhvalov/demo.adminhelper/blob/master/lib/news/news.php.

Что бы работала автозагрузка Битрикса, файлы в модуле должны называться в нижнем регистре. У моделей в названии файла слова `table` быть не должно.

**Comment by Frimko** [comment]
чекбокс он видит как boolean
`new BooleanField('ACTIVE', array(
                'required' => true,
            )),`
хотя битрикс это описывает в mysql как string, отсюда и не работоспособность виджета

**Comment by ASGAlex** [comment]
У виджета там два режима работы, по-человечески и через string. Можно выбрать подходящий в настройках виджета.

**Comment by Frimko** [comment]
т.е. ты мне предлагаешь переписать константы в самом виджете? мб там есть что-то типа настройки `protected static $defaults = array(
        'EDIT_IN_LIST' => true
    );` ?
в самом виджете к сожалению этого нету

**Comment by ASGAlex** [comment]
Можно переопределить `CheckboxWidget::getCheckboxType();` и вернуть нужный тип чекбокса. 

В настройках, внезапно, нет... надо будет добавить.

**Comment by Frimko** [comment]
Мой внутренний перфекционист в истерике забился в комочек...

**Comment by ASGAlex** [comment]
Мсье, как же вы тогда связались с битриксом?))))))

**Comment by Frimko** [comment]
"Пути до Битрикса не неисповедимы"

**Comment by Frimko** [comment]
а примера для реализации виджета OrmElementWidget не найдется?

**Comment by ASGAlex** [comment]
Только что тут #33 запилил возможность указать тип данных для чекбокса, не прибегая к наследованию, через настройки. 

@niksamokhvalov на счет OrmElementWidget - отвечать тебе.

**Comment by Frimko** [comment]
ух, как я понял представления списка(то окошечко, которое всплывает при редактировании значения) у вас нету для виджета OrmElementWidget. 
`'##название нашего поля, у которого есть связь##' => array(
                        'TITLE' => 'Пользователь',
                        'WIDGET' => new OrmElementWidget(),
                        'HELPER'=>'\Test\Web38\Comments\AdminInterface\HelperForUser',
                        'TITLE_FIELD_NAME' => 'LOGIN',
                    ),`
ну и конечно же надо описать нашего наследника 
`namespace Test\Web38\Comments\AdminInterface;
use \DigitalWand\AdminHelper\Helper\AdminBaseHelper;
abstract class HelperForUser extends AdminBaseHelper
{
    static protected $model = 'Bitrix\Test\Web38\SmilesUsersCommentTable';
    static protected $interfaceClass = array(
        'Test\Web38\Comments\AdminInterfaceUsers\UsersInterface'
    );
}`
и не забываем объявить его в модуле 
`Loader::registerAutoLoadClasses($moduleName, array(
    'Bitrix\Test\Web38\SmilesCommentTable' => 'lib/SmilesCommentTable.php',
    'Bitrix\Test\Web38\SmilesUsersAvatarTable' => 'lib/SmilesUsersAvatarTable.php',
    'Test\Web38\Comments\AdminInterface\HelperForUser' => 'lib/comments/admininterface/HelperForUser.php',
));`

**Comment by Frimko** [comment]
В EntityManager.php есть 1 небольшой недочет. При нажатии вот на эту кнопочку http://joxi.ru/52aYBNPFGpEgp2  EntityManager.php:247 $this->helper->getPk() получает массив, хотя там должно быть число
з.ы. реквесты писать пока не стану, ибо не до конца разобрался в вашем творчестве.
з.ы.2 только творец знает, что лучше для его детища

**Comment by Frimko** [comment]
route.php:112
`elseif (is_subclass_of($helper, 'DigitalWand\AdminHelper\Helper\AdminBaseHelper')) {
    $adminHelper = new $helper($fields, $tabs);
}`
Инстанс абстрактного класса?! втф

**Comment by ASGAlex** [comment]
http://php.net/manual/ru/function.is-subclass-of.php

> is_subclass_of — Проверяет, содержит ли объект в своем дереве предков указанный класс

Не вижу криминала. Инстанс наследника абстрактного класса.

**Comment by Frimko** [comment]
с ответственностью заявляю OrmElementWidget тот еще шлак, без хоть какой то документации или дампа ментаскопирования мозгов разработчика этого чуда

**Comment by Frimko** [comment]
> Не вижу криминала. Инстанс наследника абстрактного класса.

да, я просто наследовал его таким же абстрактным классом.

**Comment by niksamokhvalov** [comment]
Ничоси, какой дерзкий : )

@Frimko ты спрашивал про OrmElementWidget. Отвечаю: https://github.com/DigitalWand/digitalwand.admin_helper/blob/2.x/lib/widget/OrmElementWidget.php#L11. 

Виджет заводится с минимальными параметрами:
- WIDGET
- HELPER (подразумевается, что указан хелпер работающей админки)

**Comment by Frimko** [comment]
@niksamokhvalov а плагиатить тп Битрикса не хорошо. Тут становится куда проще накатать свое што то, чем пытаться прикрутить этот виджет.

**Comment by niksamokhvalov** [comment]
Не путай платную ТП Битрикса, за которую платят деньги, и опен-сорс, который тебе никто не навязывает и не просит использовать. Это принципиально разные концепции. И есть два пути: 1) поливать грязью труды, которыми безвозмездно поделилось сообщество, жаловаться на качество решения (совершая, при этом, детские ошибки по автолоаду классов) или 2) ясно описать проблему, с пруфами и линками, и предложить решение. Мы всегда рады конструктивной критике, issue-сам и пул-реквестам. Выбор за тобой.

> abstract class HelperForUser extends AdminBaseHelper
> да, я просто наследовал его таким же абстрактным классом.

Абстрактный класс, подсунутый ОРМ-виджету, не может исполняться. Поэтому модуль выкидывает ошибку. Могу только ещё раз процитировать важную часть моего предыдущего сообщения:

> (подразумевается, что указан хелпер работающей админки)

Абстрактный `HelperForUser` не может являться работающей админкой.

**Comment by Frimko** [comment]
@niksamokhvalov Да, согласен ошибки детские. Уже понял свою оплошность, достаточно подключить AdminListHelper и закинуть к юрл popup=Y. вот тогда все и заработает. 
з.ы. но цитировать слова из мануала, это выбесит любого. Да и мануал водянистый(считай понятен только его создателю).

**Comment by Frimko** [comment]
эх, оформления для эрмитажа не хватает...
