### ISSUE TITLE
Настройки интерфейса

### ISSUE THREAD

**Issue by niksamokhvalov** [DigitalWand/digitalwand.admin_helper#4]
Не хватает конфигов, которые бы позволяли:
- Скрывать поля в форме редактирования, но показывать их в списках.
- Управлять кнопками «сохранить», «применить», «отменить» и др.: запрещать какие-то из них отображать, добавлять свои и т. д.
- Так же, иметь возможность управлять кнопками в списках.
- Метод setElementTitle() научить читать данные из интерфейса, что бы можно было описывать массивом заголовки для страниц.

Думаю, большую часть из перечисленного лучше настраивать через Interface.php. Но после выполнения задачи #1.

**Comment by ASGAlex** [comment]
Не считаю, что это следует выносить в конфиги. Есть методы, которые отвечают за вывод: заполняют массив "умолчательными" значениями - и появляются новые кнопки. Если что-то нужно изменить, то переопределяется нужная функция и там уже заполняется массив как надо. 

Это относится к кнопкам, кнопкам в списках. setElementTitle(), если я правильно помню, вполне можно вызвать в конструкторе класса и сформировать заголовок так, как тебе оно надо. 

Для полей кажется есть какие-то настройки, нужно покопать в исходниках и задокументировать. В крайнем случае черрез переопределение функций все тоже решается. 

В общем, я считаю, что 90% из описанного сейчас есть, просто нужно изучить API. Для каждой мелочи делать по настройке тоже не вариант, их количество в перспективе тогда будет зашкаливать.

**Comment by niksamokhvalov** [comment]
Сделано во второй версии.
