### ISSUE TITLE
Удаление дочерних элементов

### ISSUE THREAD

**Issue by senor-artemisio** [DigitalWand/digitalwand.admin_helper#49]
При удалении разделов удаление дочерних элементов остается на совести модели. Даже если это все таки реализовано в модели,  то если этих элементов будет слишком много, то удаление может упасть по таймауту.

**Comment by ASGAlex** [comment]
Думаю, это и должно быть на совести модели, ей там виднее, что надо делать с дочками и когда. Если автор модели сам что-то не предусмотрел, то это, в общем, его вина. Если речь про механизм "пометки на удаление" с последующим удалением по расписанию - то это уже тема для отдельного модуля, не привязанного к конкретной реализации админки. Удалять-то можно и не через неё.
