### ISSUE TITLE
Связь многий ко многим

### ISSUE THREAD

**Issue by dmnbars** [DigitalWand/digitalwand.admin_helper#80]
Добрый день.
Подскажите, пожалуйста, поддерживает ли данный модуль из коробки возможность редактирования связи многий ко многим для OrmElementWidget?

**Comment by denx-b** [comment]
Присоединяюсь к вопросу.

**Comment by ASGAlex** [comment]
Почитал код (код не мой) - нет, не поддерживает. Только один ко многим.
