### ISSUE TITLE
Не работает групповое удаление для разделов

### ISSUE THREAD

**Issue by nook-ru** [DigitalWand/digitalwand.admin_helper#86]
Можно воспроизвести на [demo.adminhelper](https://github.com/niksamokhvalov/demo.adminhelper):

![2017-04-12_11-40-41](https://cloud.githubusercontent.com/assets/444489/24949067/0c84ac36-1f75-11e7-8c99-6ac40a16757d.gif)

**Comment by ASGAlex** [comment]
Ошибка сохраняется, если выделить элементы через галочку "для всех"

**Comment by nook-ru** [comment]
> Ошибка сохраняется, если выделить элементы через галочку "для всех"

Да, нужно переписать кусок кода, выбирающий `ID` для удаления: [/lib/helper/AdminListHelper.php#L202-L227](https://github.com/DigitalWand/digitalwand.admin_helper/blob/2.x/lib/helper/AdminListHelper.php#L202-L227). Он сейчас выбирает только элементы.

**Comment by ASGAlex** [comment]
@nook-ru спасибо за наводку, пофиксил
