### ISSUE TITLE
Ошибка удаления в списке

### ISSUE THREAD

**Issue by falur** [DigitalWand/digitalwand.admin_helper#99]
Уидает исключение

Unknown primary `0` found when trying to query OrderStatus row.

```php
$this->helper->getPk()
````

возвращает массив и в ключе 0 вмето ID

**Comment by falur** [comment]
В EntityManager в методе delete

заменить
```php
$result = $model::delete($this->helper->getPk()); // удаляем основную сущность
```
на
```php
 $result = $model::delete($this->itemId); // удаляем основную сущность
````

будет время сделаю pull request

**Comment by denx-b** [comment]
Ишью можно закрыть, проблема, как я вижу, уже решена.
